version: '2'
services:
    jhipstermscvsgateway-app:
        image: jhipstermscvsgateway
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATA_MONGODB_URI=mongodb://jhipstermscvsgateway-mongodb:27017
            - SPRING_DATA_MONGODB_DATABASE=jhipstermscvsgateway
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8084:8084
    jhipstermscvsgateway-mongodb:
        extends:
            file: mongodb.yml
            service: jhipstermscvsgateway-mongodb
